travis:
  secure:
    BINSTAR_TOKEN: FcrEdDv0xLUpvq7BygAKDcursNrVe4PtKGKyMjsq1C+g6oTwH5vllmw4Rs4c0zQmlOa7bwfses+jkYSltCkcEwccDYrhMbHnXolIjbROVdbihVbSqc6Xbxse9oDhWa6PDRew+UyMXDBBPKj4Ur4MjPqpI2g0IeU+bBAGUsBJDLqd9k3Ee6T4D8Z5smPELyCLTGoIxdQsE0dofhlgUiroS3pdbaOjNchtKgBLERMlgVcP4A5y73MO04CQ7BwdWZW+amZQ5gJCIt8yHiL4xS6ilkWc21o57jif8v9cB9JR3Cn6ITgr0wWzDTwk8ZXFKZTkTdl+w7Mkb9r6Fi2C9t5ml6qbLdOD2yFwIuNa8Wgn+WGSrohce0Gzokny9hjF4hITgNuv8YnQ6JUpKMeZP0AMknX7QoEneS9C28cY8ABnH1uGNKCVaJbV39hQNrIKIIV98Tzzi2UKyId1bzwelxMlK+wqnmsLTk+AJXfnWI9BKcC2RKYUX4dyuvN/J26EOmAvtKU4D315nZK24pnPMGIzIvoOBXDYzUqN4O7EB+QVFtM6F6G9m7Y9eT2pnunh2M1T4xWUHrzfooIN/0rnL5ZSJPWdEjVVdetL33LMw0EetkUP5svEF136UWOLld7ZbwXSteWx0i4/4DyNMkQjDyPCfwNP8/1gobQMqi9xWC9g378=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
