travis:
  secure:
    BINSTAR_TOKEN: c602JfJB0V9IT0BAWCF0VlvhQieKYa/C0IZ/nJmq3ciurmXyucTBWWzCNj8AtTSK0vqM6Yu9ygly6V95Afxy8DUNoCcaAXDgmhzlS/jRwOWQcvLPjBnoRUi44oj77LcZlTPDxwT6wUIX7enFCOMTNfdDC+AtLllhpSKvVUE1J2i29x0nWbxesCd4vxO3bFrD0dj1e7zNjhavSfwuboDp8SItL6CTisC1rzZ7ZkvxuWCXVn6OfxulcDV2gcbXWpom7eWdci7cqXbv13ZEAy2nl1UAIf8999h5HQni6bDZpUY7Gzcs9O3AL7XreZ0MvpfU5ltIArDylV/eQOinXG+4m9EoS9a3d0ksH301fUd8ENbbUgANgUbOhh2T7p2dCb1yM3ASeGR6AHUk68T++NaVr5JN4Ia3HZQ9edL4AuhSCL/dxVntmmeL+JtIlWSppER1YdBypme7JmWoA4R8bagWLj4AMoEYjt+bedTtbxFRNT2BrdJD//E0bN+yMxf+iFo4FvcQTf0+TSbGryPbwxQaudTvbmviPHlp9Mh/DxT91xjY+16xUmZt2nQBflknkH0Vhudvk0j0Vo6XSFMV4WPYhToJL2xrGXDkESedmlVyQn1v9yR+VoFG9BSEV99QpujIhg4ojKV0u1r91HCuWk9O7d2YQJSN9zOoclUfAwtb8YE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
