travis:
  secure:
    BINSTAR_TOKEN: feRMCt+5F+mgFHXLjq04QrvWdKVsDF0X4PYmeiMAUviVQQ+/YByihn4hngMTMtP5pxb2Q+uE8bAz2GSnb/BQQmnhl9fR5L3s/gkrTLmaiW9URiUTYtDyqwt6tMg6zcQvU99YQeR6zalg3bYwXvEtDkhjXna7e1+uq4k2/qPgD3JWaovQ33W+8OiWIvkcp08sbIbK3xfxTY+fbGzgPzpyqrrbNxC0B9rQdeHFr+PwNe4gTQE7fTg4G1UmR0gnPvcZkR1kNZ7zDoEZejJOJArGc7LMiU4VK5jf2mHDsvLEpnssF+xDOR1f9WnqlqT0wjvaVL0wG/jPpbDzsl1Nbi+xHX6P1V0YFdMa6QP7Znoh6nX5arF7UDCOeu4d1j9q2BfMBm4lFz0UKS+lPqnUVkFD7ZcolIsxQt3GUrkT/h1EYpT01mxq8IVsymQye2mjI2vNT3hUeH0or4Bgjq5wIpBc9SqwmZsG6CuePFpB3Iv6qYIt8ursiddKzA34K2vKTPqEeaCVH9+BMrbFrgqx8/sslaVawGvnAyh1ZFqIPj4E65FDtLs9dYWOTTUE5TLsPThQnZD1NJweEkgZzUCfLthHowLQIT90i5w6Dl9LxY71nXQ3rBozyfb9rOnm37G8M0XkoCcsme2GHBI7r3hO9+42JDpuHWjHuZL7I7oOC6TUwE8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
